name: Publish

on:
  push:
    branches:
      - main

permissions:
  contents: read
  id-token: write

jobs:
  ci:
    uses: makerxstudio/shared-config/.github/workflows/node-ci.yml@bf6a061f099c9b66e7134a8ec1e4a37f4b0eaf02 # v2.0.1
    with:
      compile-script: npm run typecheck
      pre-test-script: npx playwright install --with-deps chromium
      test-script: npm run test:coverage
      audit-script: npm run audit

  publish:
    needs: ci
    uses: makerxstudio/shared-config/.github/workflows/node-trusted-publish.yml@bf6a061f099c9b66e7134a8ec1e4a37f4b0eaf02 # v2.0.1
    with:
      package-path: './package.json'
      access: public
